# Generated by Django 4.1 on 2022-08-23 10:29

import Extentions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email_address', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read?')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DegreeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Extentions.utils.degree_image_path, verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('created', models.DateTimeField(verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Degree',
                'verbose_name_plural': 'Degrees',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('from_date', models.DateField(verbose_name='From')),
                ('to_date', models.DateField(verbose_name='To')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('from_date', models.DateField(verbose_name='From')),
                ('to_date', models.DateField(verbose_name='To')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full Name')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Sub Title')),
                ('profile', models.ImageField(upload_to=Extentions.utils.user_image_path, verbose_name='Profile')),
                ('age', models.PositiveIntegerField(verbose_name='Percent')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('skype', models.CharField(max_length=255, verbose_name='Skype')),
                ('phone', models.PositiveBigIntegerField(verbose_name='Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('aboutme', models.TextField(verbose_name='Description')),
                ('x', models.FloatField(verbose_name='X')),
                ('y', models.FloatField(verbose_name='Y')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(max_length=255, verbose_name='GitHub')),
                ('instagram', models.CharField(max_length=255, verbose_name='Instagram')),
                ('linkedin', models.CharField(max_length=255, verbose_name='LinkedIn')),
                ('telegram', models.CharField(max_length=255, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Extentions.utils.portfolio_image_path, verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Full Name')),
                ('techs', models.CharField(max_length=255, verbose_name='Full Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateField(verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to=Extentions.utils.user_image_path, verbose_name='Profile')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('ref_title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateField(verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, verbose_name='Skill')),
                ('percent', models.PositiveIntegerField(verbose_name='Percent')),
                ('title', models.CharField(choices=[('beginner', 'BEGINNER'), ('expert', 'EXPERT'), ('master', 'MASTER'), ('advance', 'ADVANCE')], max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-id'],
            },
        ),
    ]
