# Generated by Django 4.1 on 2022-08-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillmodel',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='aboutme',
            field=models.TextField(verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='techs',
            field=models.CharField(max_length=255, verbose_name='Technologies'),
        ),
    ]
