# Generated by Django 4.1 on 2022-08-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_languagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagemodel',
            old_name='Reading',
            new_name='reading',
        ),
        migrations.RenameField(
            model_name='languagemodel',
            old_name='Speaking',
            new_name='speaking',
        ),
        migrations.RenameField(
            model_name='languagemodel',
            old_name='Writing',
            new_name='writing',
        ),
    ]
